galaxy_info:
  author: AveLegatus
  description: Docker Engine for Linux
  company: HomeBrew

  license: "license (Apache-2.0)"

  min_ansible_version: 2.9

  platforms:
   - name: Ubuntu
     versions:
        - xenial
        - bionic
        - focal
   - name: Debian
     versions:
        - stretch
        - buster
   - name: CentOS
     versions:
     - 7

  galaxy_tags:
    - docker
    - container
